import type { PlacementQuestion } from '@/types'

export const PLACEMENT_QUESTIONS: PlacementQuestion[] = [
  {
    id: 'l1',
    phase: 'listening',
    phase_label: 'Compreensão Auditiva',
    phase_emoji: '👂',
    prompt_tts: 'Hello! What is your name? Tell me a little about yourself.',
    prompt_display: 'A professora vai falar com você. Responda em inglês.',
    expected_topic: 'self_introduction',
    difficulty: 'easy',
  },
  {
    id: 'l2',
    phase: 'listening',
    phase_label: 'Compreensão Auditiva',
    phase_emoji: '👂',
    prompt_tts: 'Can you describe your typical morning routine? What do you usually do first?',
    prompt_display: 'Responda sobre sua rotina matinal em inglês.',
    expected_topic: 'daily_routine_present_simple',
    difficulty: 'medium',
  },
  {
    id: 's1',
    phase: 'speaking',
    phase_label: 'Fala',
    phase_emoji: '🗣️',
    prompt_tts: 'Where are you from? Tell me about your city or town.',
    prompt_display: 'Fale sobre de onde você é e sua cidade.',
    expected_topic: 'origin_description',
    difficulty: 'easy',
  },
  {
    id: 's2',
    phase: 'speaking',
    phase_label: 'Fala',
    phase_emoji: '🗣️',
    prompt_tts: 'What do you like to do on weekends? Any hobbies?',
    prompt_display: 'Fale sobre suas atividades e hobbies favoritos.',
    expected_topic: 'hobbies_and_preferences',
    difficulty: 'medium',
  },
  {
    id: 's3',
    phase: 'speaking',
    phase_label: 'Fala',
    phase_emoji: '🗣️',
    prompt_tts: 'Tell me about a memorable trip or experience you have had.',
    prompt_display: 'Conte sobre uma viagem ou experiência marcante.',
    expected_topic: 'past_experience_narrative',
    difficulty: 'hard',
  },
  {
    id: 'v1',
    phase: 'vocabulary',
    phase_label: 'Vocabulário',
    phase_emoji: '📚',
    prompt_tts: 'What is this? 🏥 Say the word in English.',
    prompt_display: 'O que é isso? 🏥 Diga a palavra em inglês.',
    expected_topic: 'hospital',
    difficulty: 'easy',
  },
  {
    id: 'v2',
    phase: 'vocabulary',
    phase_label: 'Vocabulário',
    phase_emoji: '📚',
    prompt_tts: 'Look at this: 🗓️ What do you call this in English? Use it in a sentence.',
    prompt_display: 'O que é isso? 🗓️ Use a palavra em uma frase em inglês.',
    expected_topic: 'calendar_schedule',
    difficulty: 'medium',
  },
  {
    id: 'g1',
    phase: 'grammar',
    phase_label: 'Gramática',
    phase_emoji: '✏️',
    prompt_tts: 'Yesterday was your day off. Tell me, what did you do?',
    prompt_display: 'Ontem foi seu dia de folga. Conte o que você fez em inglês.',
    expected_topic: 'past_simple_tense',
    difficulty: 'medium',
  },
  {
    id: 'g2',
    phase: 'grammar',
    phase_label: 'Gramática',
    phase_emoji: '✏️',
    prompt_tts: 'If you could live anywhere in the world, where would you choose and why?',
    prompt_display: 'Se pudesse morar em qualquer lugar, onde seria? Responda em inglês.',
    expected_topic: 'second_conditional',
    difficulty: 'hard',
  },
  {
    id: 'p1',
    phase: 'pronunciation',
    phase_label: 'Pronúncia',
    phase_emoji: '🎤',
    prompt_tts: 'Please repeat after me: THINK, THREE, THROUGH, THANK YOU.',
    prompt_display: 'Repita em voz alta: THINK, THREE, THROUGH, THANK YOU',
    expected_topic: 'TH_sound_clarity',
    difficulty: 'easy',
  },
]
