// lib/topics.ts
import type { CefrLevel } from '@/types'

export interface Topic {
  key: string
  labelPt: string
  promptEn: string
  emoji: string
  objectivesPt: string[]
  starterPhrase: string
  estimatedMinutes: number
}

const TOPICS_BY_LEVEL: Partial<Record<CefrLevel, Topic[]>> = {
  A1: [
    {
      key: 'introductions',
      labelPt: 'Apresentações pessoais',
      promptEn: 'personal introductions: name, age, nationality, and what you do',
      emoji: '👋',
      objectivesPt: ['Dizer seu nome e de onde você é', 'Falar sua idade em inglês', 'Apresentar-se naturalmente'],
      starterPhrase: 'Hello! My name is ___.',
      estimatedMinutes: 8,
    },
    {
      key: 'family',
      labelPt: 'Família',
      promptEn: 'describing family members: who they are and what they do',
      emoji: '👨‍👩‍👧',
      objectivesPt: ['Descrever membros da família', 'Dizer o que cada um faz', 'Usar possessivos: my, his, her'],
      starterPhrase: 'Hello! I want to talk about my family.',
      estimatedMinutes: 8,
    },
    {
      key: 'numbers-dates',
      labelPt: 'Números e datas',
      promptEn: 'numbers, dates, and days of the week',
      emoji: '📅',
      objectivesPt: ['Contar de 1 a 100 em inglês', 'Dizer datas e dias da semana', 'Perguntar o horário'],
      starterPhrase: 'Hello! Can we practice numbers?',
      estimatedMinutes: 8,
    },
    {
      key: 'colors',
      labelPt: 'Cores e adjetivos',
      promptEn: 'colors, shapes, and basic descriptive adjectives',
      emoji: '🎨',
      objectivesPt: ['Nomear as cores básicas', 'Descrever objetos com adjetivos', 'Usar "It is" e "They are"'],
      starterPhrase: 'Hello! I love colors.',
      estimatedMinutes: 8,
    },
    {
      key: 'daily-routine',
      labelPt: 'Rotina diária',
      promptEn: 'describing your daily routine from morning to night',
      emoji: '⏰',
      objectivesPt: ['Contar sua rotina do dia', 'Usar verbos no presente simples', 'Falar horários em inglês'],
      starterPhrase: 'Hello! I wake up at 7am every day.',
      estimatedMinutes: 8,
    },
    {
      key: 'food',
      labelPt: 'Comida e bebida',
      promptEn: 'food and drinks: what you like and what you eat for each meal',
      emoji: '🍕',
      objectivesPt: ['Nomear alimentos e bebidas', 'Dizer o que você gosta', 'Falar sobre suas refeições'],
      starterPhrase: 'Hello! I love Brazilian food.',
      estimatedMinutes: 8,
    },
    {
      key: 'greetings',
      labelPt: 'Cumprimentos',
      promptEn: 'greetings, farewells, and polite expressions',
      emoji: '😊',
      objectivesPt: ['Cumprimentar em inglês', 'Se despedir corretamente', 'Usar expressões educadas'],
      starterPhrase: 'Hello! How are you today?',
      estimatedMinutes: 8,
    },
    {
      key: 'home',
      labelPt: 'Minha casa',
      promptEn: 'describing your home: rooms, furniture, and where things are',
      emoji: '🏠',
      objectivesPt: ['Descrever os cômodos da sua casa', 'Falar sobre móveis', 'Dizer onde as coisas estão'],
      starterPhrase: 'Hello! I want to describe my house.',
      estimatedMinutes: 8,
    },
  ],
  A2: [
    {
      key: 'past-weekend',
      labelPt: 'Fim de semana',
      promptEn: 'what you did last weekend using past simple tense',
      emoji: '📸',
      objectivesPt: ['Usar o passado simples em inglês', 'Contar o que fez no fim de semana', 'Fazer perguntas no passado'],
      starterPhrase: 'Hello! I had a great weekend.',
      estimatedMinutes: 10,
    },
    {
      key: 'city',
      labelPt: 'Minha cidade',
      promptEn: 'describing your city or neighborhood: places, transport, and atmosphere',
      emoji: '🏙️',
      objectivesPt: ['Descrever sua cidade ou bairro', 'Falar sobre lugares importantes', 'Usar "there is / there are"'],
      starterPhrase: 'Hello! I live in a big city.',
      estimatedMinutes: 10,
    },
    {
      key: 'shopping',
      labelPt: 'Compras',
      promptEn: 'shopping: prices, sizes, preferences, and asking for help in stores',
      emoji: '🛍️',
      objectivesPt: ['Pedir ajuda em uma loja', 'Falar sobre preços e tamanhos', 'Expressar preferências'],
      starterPhrase: 'Hello! I love shopping on weekends.',
      estimatedMinutes: 10,
    },
    {
      key: 'weather',
      labelPt: 'Clima e estações',
      promptEn: 'talking about weather, seasons, and how they affect daily life',
      emoji: '☀️',
      objectivesPt: ['Descrever o clima em inglês', 'Falar sobre as estações do ano', 'Perguntar sobre o tempo'],
      starterPhrase: 'Hello! The weather here is very hot.',
      estimatedMinutes: 10,
    },
    {
      key: 'hobbies',
      labelPt: 'Hobbies',
      promptEn: 'hobbies and free-time activities: what you enjoy doing and why',
      emoji: '🎸',
      objectivesPt: ['Falar sobre seus hobbies', 'Usar "I like / I enjoy"', 'Explicar por que você gosta'],
      starterPhrase: 'Hello! In my free time I like to read.',
      estimatedMinutes: 10,
    },
    {
      key: 'transport',
      labelPt: 'Transporte',
      promptEn: 'transportation and asking for directions around the city',
      emoji: '🚗',
      objectivesPt: ['Pedir informações de transporte', 'Perguntar direções', 'Falar como você se locomove'],
      starterPhrase: 'Hello! How do I get to the airport?',
      estimatedMinutes: 10,
    },
    {
      key: 'work',
      labelPt: 'Trabalho',
      promptEn: 'talking about jobs, workplaces, and daily work activities',
      emoji: '💼',
      objectivesPt: ['Falar sobre seu trabalho', 'Descrever suas tarefas do dia', 'Fazer perguntas sobre profissões'],
      starterPhrase: 'Hello! I work as a software developer.',
      estimatedMinutes: 10,
    },
    {
      key: 'health',
      labelPt: 'Saúde',
      promptEn: 'health: describing symptoms, visiting the doctor, and getting better',
      emoji: '🏥',
      objectivesPt: ['Descrever sintomas em inglês', 'Falar sobre saúde e bem-estar', 'Usar "I feel" e "I have a"'],
      starterPhrase: 'Hello! I want to talk about health.',
      estimatedMinutes: 10,
    },
  ],
  B1: [
    {
      key: 'travel',
      labelPt: 'Viagens',
      promptEn: 'travel experiences: places visited, adventures, and future travel plans',
      emoji: '✈️',
      objectivesPt: ['Contar experiências de viagem', 'Falar planos futuros', 'Usar present perfect para experiências'],
      starterPhrase: 'Hello! I love traveling to new places.',
      estimatedMinutes: 12,
    },
    {
      key: 'news',
      labelPt: 'Notícias e opinião',
      promptEn: 'sharing opinions about news and current events in the world',
      emoji: '📰',
      objectivesPt: ['Dar sua opinião sobre notícias', 'Usar "I think / I believe"', 'Argumentar e contra-argumentar'],
      starterPhrase: 'Hello! Have you seen the news today?',
      estimatedMinutes: 12,
    },
    {
      key: 'future',
      labelPt: 'Planos futuros',
      promptEn: 'future plans: goals, dreams, and what you are planning to do',
      emoji: '🚀',
      objectivesPt: ['Falar sobre metas e sonhos', 'Usar "will" e "going to"', 'Expressar certeza e incerteza'],
      starterPhrase: 'Hello! I have big plans for this year.',
      estimatedMinutes: 12,
    },
    {
      key: 'problems',
      labelPt: 'Problemas e soluções',
      promptEn: 'describing real-life problems and brainstorming practical solutions',
      emoji: '💡',
      objectivesPt: ['Descrever um problema', 'Sugerir soluções', 'Usar "should / could / might"'],
      starterPhrase: 'Hello! I need your advice on something.',
      estimatedMinutes: 12,
    },
    {
      key: 'entertainment',
      labelPt: 'Filmes e séries',
      promptEn: 'movies, TV series, and books: recommendations and personal reviews',
      emoji: '🎬',
      objectivesPt: ['Recomendar filmes e séries', 'Dar opiniões detalhadas', 'Descrever enredo sem spoilers'],
      starterPhrase: 'Hello! I just watched an amazing movie.',
      estimatedMinutes: 12,
    },
    {
      key: 'culture',
      labelPt: 'Diferenças culturais',
      promptEn: 'cultural differences between Brazil and English-speaking countries',
      emoji: '🌍',
      objectivesPt: ['Comparar culturas', 'Falar sobre costumes brasileiros', 'Expressar surpresa e curiosidade'],
      starterPhrase: 'Hello! Brazil and the US are so different.',
      estimatedMinutes: 12,
    },
    {
      key: 'career',
      labelPt: 'Carreira',
      promptEn: 'career goals, job ambitions, and professional development',
      emoji: '📈',
      objectivesPt: ['Falar sobre sua carreira', 'Expressar ambições profissionais', 'Discutir desenvolvimento pessoal'],
      starterPhrase: 'Hello! I want to grow in my career.',
      estimatedMinutes: 12,
    },
    {
      key: 'restaurants',
      labelPt: 'Restaurantes',
      promptEn: 'restaurants, food preferences, and dining-out etiquette',
      emoji: '🍽️',
      objectivesPt: ['Fazer um pedido em inglês', 'Falar sobre preferências alimentares', 'Recomendar restaurantes'],
      starterPhrase: 'Hello! I love trying new restaurants.',
      estimatedMinutes: 12,
    },
  ],
  B2: [
    {
      key: 'social-media',
      labelPt: 'Redes sociais',
      promptEn: 'debating the impact of social media on mental health and society',
      emoji: '📱',
      objectivesPt: ['Debater o impacto das redes sociais', 'Construir argumentos estruturados', 'Usar vocabulário de debate'],
      starterPhrase: 'Hello! Social media has changed everything.',
      estimatedMinutes: 15,
    },
    {
      key: 'environment',
      labelPt: 'Meio ambiente',
      promptEn: 'environmental issues: climate change, sustainability, and solutions',
      emoji: '🌱',
      objectivesPt: ['Discutir mudanças climáticas', 'Propor soluções sustentáveis', 'Usar vocabulário ambiental'],
      starterPhrase: 'Hello! I care deeply about the environment.',
      estimatedMinutes: 15,
    },
    {
      key: 'technology',
      labelPt: 'Tecnologia e IA',
      promptEn: 'technology and artificial intelligence: opportunities and risks for society',
      emoji: '🤖',
      objectivesPt: ['Analisar impactos da IA', 'Discutir oportunidades e riscos', 'Expressar nuances de opinião'],
      starterPhrase: 'Hello! AI is transforming our world.',
      estimatedMinutes: 15,
    },
    {
      key: 'education',
      labelPt: 'Educação',
      promptEn: 'education systems: comparing approaches, challenges, and reforms',
      emoji: '📚',
      objectivesPt: ['Comparar sistemas de ensino', 'Discutir desafios educacionais', 'Propor reformas'],
      starterPhrase: 'Hello! Education is the key to everything.',
      estimatedMinutes: 15,
    },
    {
      key: 'finance',
      labelPt: 'Finanças',
      promptEn: 'personal finance: budgeting, investing, and financial planning',
      emoji: '💰',
      objectivesPt: ['Discutir finanças pessoais', 'Falar sobre investimentos', 'Usar vocabulário financeiro'],
      starterPhrase: 'Hello! Financial planning is so important.',
      estimatedMinutes: 15,
    },
    {
      key: 'relationships',
      labelPt: 'Relacionamentos',
      promptEn: 'relationships and communication: what makes them work and what causes problems',
      emoji: '❤️',
      objectivesPt: ['Discutir dinâmicas de relacionamentos', 'Analisar comunicação interpessoal', 'Expressar emoções com nuance'],
      starterPhrase: 'Hello! Communication is key in any relationship.',
      estimatedMinutes: 15,
    },
    {
      key: 'leadership',
      labelPt: 'Liderança',
      promptEn: 'leadership and teamwork: qualities, challenges, and different styles',
      emoji: '🏆',
      objectivesPt: ['Discutir estilos de liderança', 'Analisar trabalho em equipe', 'Usar vocabulário de gestão'],
      starterPhrase: 'Hello! Great leadership makes all the difference.',
      estimatedMinutes: 15,
    },
    {
      key: 'ethics',
      labelPt: 'Ética',
      promptEn: 'ethics and moral dilemmas: discussing complex right-versus-wrong scenarios',
      emoji: '⚖️',
      objectivesPt: ['Analisar dilemas éticos', 'Construir argumentos morais', 'Discutir perspectivas opostas'],
      starterPhrase: 'Hello! Ethics shapes every decision we make.',
      estimatedMinutes: 15,
    },
  ],
  C1: [
    {
      key: 'job-interview',
      labelPt: 'Entrevista de emprego',
      promptEn: 'role-play a professional job interview for a position in your field, using structured answers and formal register',
      emoji: '🤝',
      objectivesPt: ['Simular entrevista profissional', 'Usar linguagem formal e estruturada', 'Dominar perguntas comportamentais'],
      starterPhrase: 'Hello! I\'m here for the interview.',
      estimatedMinutes: 20,
    },
    {
      key: 'negotiation',
      labelPt: 'Negociação',
      promptEn: 'simulate a business negotiation: setting terms, making concessions, and reaching agreement professionally',
      emoji: '📋',
      objectivesPt: ['Conduzir negociação profissional', 'Fazer concessões estratégicas', 'Chegar a acordos diplomaticamente'],
      starterPhrase: 'Hello! I\'d like to discuss our proposal.',
      estimatedMinutes: 20,
    },
    {
      key: 'ted-talk',
      labelPt: 'Análise crítica',
      promptEn: 'summarize and critically analyze the arguments from a talk, documentary, or article you have engaged with recently',
      emoji: '🎤',
      objectivesPt: ['Resumir argumentos complexos', 'Analisar criticamente ideias', 'Expressar concordância e discordância nuançada'],
      starterPhrase: 'Hello! I recently watched a fascinating talk.',
      estimatedMinutes: 20,
    },
    {
      key: 'abstract-concepts',
      labelPt: 'Conceitos abstratos',
      promptEn: 'discuss abstract concepts like justice, identity, or success with nuance, counterarguments, and concrete examples',
      emoji: '🧠',
      objectivesPt: ['Discutir conceitos abstratos', 'Usar contra-argumentos', 'Exemplificar com casos concretos'],
      starterPhrase: 'Hello! What does success mean to you?',
      estimatedMinutes: 20,
    },
    {
      key: 'idioms',
      labelPt: 'Expressões idiomáticas',
      promptEn: 'use and explain English idioms, fixed phrases, and collocations naturally in the flow of conversation',
      emoji: '💬',
      objectivesPt: ['Usar idioms naturalmente', 'Explicar expressões fixas', 'Dominar colocações em inglês'],
      starterPhrase: 'Hello! Let\'s hit the ground running!',
      estimatedMinutes: 20,
    },
    {
      key: 'meeting-simulation',
      labelPt: 'Reunião de trabalho',
      promptEn: 'conduct a full work meeting simulation covering agenda, project updates, problem-solving, and action items',
      emoji: '👔',
      objectivesPt: ['Conduzir reunião em inglês', 'Apresentar atualizações de projeto', 'Definir ações e responsáveis'],
      starterPhrase: 'Hello! Let\'s call this meeting to order.',
      estimatedMinutes: 20,
    },
    {
      key: 'persuasion',
      labelPt: 'Argumento persuasivo',
      promptEn: 'construct and defend a persuasive argument on a controversial topic using evidence, concessions, and rhetoric',
      emoji: '🎯',
      objectivesPt: ['Construir argumento persuasivo', 'Usar evidências e retórica', 'Fazer concessões estratégicas'],
      starterPhrase: 'Hello! I\'d like to make a case for something.',
      estimatedMinutes: 20,
    },
    {
      key: 'storytelling',
      labelPt: 'Narrativa avançada',
      promptEn: 'tell a personal story with full narrative structure: setup, tension, climax, resolution, and reflective closing',
      emoji: '📖',
      objectivesPt: ['Contar história com estrutura narrativa', 'Criar tensão e clímax', 'Fechar com reflexão'],
      starterPhrase: 'Hello! I have an incredible story to share.',
      estimatedMinutes: 20,
    },
  ],
  C2: [
    {
      key: 'native-humor',
      labelPt: 'Humor e ironia',
      promptEn: 'discuss jokes, sarcasm, wordplay, and irony in American and British culture and why they resonate or fail across cultures',
      emoji: '😄',
      objectivesPt: ['Discutir humor em inglês nativo', 'Entender sarcasmo e ironia', 'Analisar diferenças culturais no humor'],
      starterPhrase: 'Hello! Why did the English teacher break up with the grammar book?',
      estimatedMinutes: 25,
    },
    {
      key: 'literature',
      labelPt: 'Literatura em inglês',
      promptEn: 'analyze a passage, theme, or character from an English-language novel, poem, or film with literary vocabulary',
      emoji: '📜',
      objectivesPt: ['Analisar literatura em inglês', 'Usar vocabulário literário avançado', 'Discutir temas e personagens'],
      starterPhrase: 'Hello! Let\'s talk about a great English novel.',
      estimatedMinutes: 25,
    },
    {
      key: 'cultural-reference',
      labelPt: 'Referências culturais',
      promptEn: 'explore the pop culture references, historical allusions, and in-jokes that native speakers use without explanation',
      emoji: '🎭',
      objectivesPt: ['Entender referências culturais nativas', 'Usar alusões históricas', 'Dominar in-jokes anglófonos'],
      starterPhrase: 'Hello! I\'ve been binging American shows lately.',
      estimatedMinutes: 25,
    },
    {
      key: 'register-shift',
      labelPt: 'Registro formal vs casual',
      promptEn: 'fluidly switch between formal prose, casual conversation, and colloquial slang within a single exchange',
      emoji: '🎭',
      objectivesPt: ['Transitar entre registros formais e casuais', 'Usar gírias corretamente', 'Adaptar linguagem ao contexto'],
      starterPhrase: 'Hello! So, like, shall we commence our linguistic endeavour?',
      estimatedMinutes: 25,
    },
    {
      key: 'accents-dialects',
      labelPt: 'Sotaques e dialetos',
      promptEn: 'discuss regional accents, dialects, and sociolects in English and what they reveal about identity and class',
      emoji: '🗺️',
      objectivesPt: ['Discutir sotaques regionais', 'Analisar dialetos e socioletos', 'Explorar identidade através da fala'],
      starterPhrase: 'Hello! Accents reveal so much about where we\'re from.',
      estimatedMinutes: 25,
    },
    {
      key: 'philosophy',
      labelPt: 'Filosofia e pensamento',
      promptEn: 'engage in a Socratic dialogue on a philosophical question without simplifying — push definitions, explore contradictions',
      emoji: '🦉',
      objectivesPt: ['Conduzir diálogo socrático', 'Explorar contradições filosóficas', 'Defender posições com rigor'],
      starterPhrase: 'Hello! If a tree falls in the forest and no one hears it...',
      estimatedMinutes: 25,
    },
    {
      key: 'spontaneous-debate',
      labelPt: 'Debate espontâneo',
      promptEn: 'defend an assigned position (agree or disagree) without preparation, pivoting dynamically as arguments evolve',
      emoji: '⚡',
      objectivesPt: ['Debater sem preparação', 'Pivotar argumentos dinamicamente', 'Usar retórica avançada em tempo real'],
      starterPhrase: 'Hello! I\'ll argue any side of any topic. Go!',
      estimatedMinutes: 25,
    },
    {
      key: 'advanced-vocabulary',
      labelPt: 'Vocabulário sofisticado',
      promptEn: 'use advanced vocabulary precisely: choose the mot juste, distinguish near-synonyms, explain connotations and register',
      emoji: '🔤',
      objectivesPt: ['Escolher o mot juste', 'Distinguir quase-sinônimos', 'Explicar conotações e registro'],
      starterPhrase: 'Hello! Let\'s be precise and erudite today.',
      estimatedMinutes: 25,
    },
  ],
}

export function pickTopic(cefrLevel: CefrLevel | null | undefined, completedSessionCount: number): Topic | null {
  const topics = TOPICS_BY_LEVEL[cefrLevel ?? 'A1'] ?? TOPICS_BY_LEVEL['A1']!
  return topics[completedSessionCount % topics.length] ?? null
}

export function getTopicByKey(key: string | null | undefined): Topic | null {
  if (!key) return null
  for (const topics of Object.values(TOPICS_BY_LEVEL)) {
    const found = topics?.find((t) => t.key === key)
    if (found) return found
  }
  return null
}

export function getTopicsForLevel(cefrLevel: string | null | undefined): Topic[] {
  return TOPICS_BY_LEVEL[(cefrLevel ?? 'A1') as CefrLevel] ?? TOPICS_BY_LEVEL['A1'] ?? []
}
